apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx-deployment
spec:
  ports:
    - port: 80
      name: nginx-service80
      protocol: TCP
      targetPort: 80
      nodePort: 80
    - port: 81
      name: nginx-service81
      protocol: TCP
      targetPort: 81
      nodePort: 81
  selector:
    app: nginx
  type: NodePort